void comp_next ( int n, int k, int a[], bool *more, int *h,  int *t );
void line_o01 ( double w[], double x[] );
void line_o02 ( double w[], double x[] );
void line_o03 ( double w[], double x[] );
void line_o04 ( double w[], double x[] );
void line_o05 ( double w[], double x[] );
double *monomial_value ( int m, int n, int e[], double x[] );
void r8mat_write ( string output_filename, int m, int n, double table[] );
void r8vec_copy ( int n, double a1[], double a2[] );
double r8vec_dot_product ( int n, double a1[], double a2[] );
double *r8vec_ones_new ( int n );
void subcomp_next ( int n, int k, int a[], bool *more, int *h, int *t );
void timestamp ( );
void triangle_o01 ( double w[], double xy[] );
void triangle_o03 ( double w[], double xy[] );
void triangle_o03b ( double w[], double xy[] );
void triangle_o06 ( double w[], double xy[] );
void triangle_o06b ( double w[], double xy[] );
void triangle_o07 ( double w[], double xy[] );
void triangle_o12 ( double w[], double xy[] );
double wedge_integral ( int expon[3] );
void wedge_rule ( int line_order, int triangle_order, double w[], double xyz[] );
double wedge_volume ( );
