void disk_rule ( int nr, int nt, double w[], double r[], double t[] );
double disk01_monomial_integral ( int e[2] );
void imtqlx ( int n, double d[], double e[], double z[] );
void legendre_ek_compute ( int n, double x[], double w[] );
double r8_abs ( double x );
double r8_epsilon ( );
double r8_gamma ( double x );
double r8_sign ( double x );
void r8vec_print ( int n, double a[], string title );
void timestamp ( );
