void p00_dat ( int prob, int data_num, double x[], double y[] );
int p00_data_num ( int prob );
int p00_prob_num ( );
void p00_story ( int prob );
string p00_title ( int prob );
void p01_dat ( int data_num, double x[], double y[] );
int p01_data_num ( );
void p01_story ( );
string p01_title ( );
void p02_dat ( int data_num, double x[], double y[] );
int p02_data_num ( );
void p02_story ( );
string p02_title ( );
void p03_dat ( int data_num, double x[], double y[] );
int p03_data_num ( );
void p03_story ( );
string p03_title ( );
void p04_dat ( int data_num, double x[], double y[] );
int p04_data_num ( );
void p04_story ( );
string p04_title ( );
void p05_dat ( int data_num, double x[], double y[] );
int p05_data_num ( );
void p05_story ( );
string p05_title ( );
void p06_dat ( int data_num, double x[], double y[] );
int p06_data_num ( );
void p06_story ( );
string p06_title ( );
void p07_dat ( int data_num, double x[], double y[] );
int p07_data_num ( );
void p07_story ( );
string p07_title ( );
void p08_dat ( int data_num, double x[], double y[] );
int p08_data_num ( );
void p08_story ( );
string p08_title ( );
void p09_dat ( int data_num, double x[], double y[] );
int p09_data_num ( );
void p09_story ( );
string p09_title ( );
void p10_dat ( int data_num, double x[], double y[] );
int p10_data_num ( );
void p10_story ( );
string p10_title ( );
void r8vec_copy ( int n, double a1[], double a2[] );
void r8vec2_print ( int n, double a1[], double a2[], string title );
void r8vec2_write ( string output_filename, int n, double x[], double y[] );
