double csevl ( double x, double a[], int n );
int i4vec_sum ( int n, int a[] );
int inits ( double dos[], int nos, double eta );
double *p00_c ( int prob, int m, int &seed );
double *p00_d ( int prob, int m, int id, double c[], double w[], int n, 
  double x[] );
double *p00_f ( int prob, int m, double c[], double w[], int n, double x[] );
int p00_prob_num ( );
double p00_q ( int prob, int m, double c[], double w[] );
string p00_title ( int prob );
double *p00_w ( int prob, int m, int &seed );
double *p01_d ( int m, int id, double c[], double w[], int n, double x[] );
double *p01_f ( int m, double c[], double w[], int n, double x[] );
double p01_q ( int m, double c[], double w[] );
string p01_title ( );
double *p02_d ( int m, int id, double c[], double w[], int n, double x[] );
double *p02_f ( int m, double c[], double w[], int n, double x[] );
double p02_q ( int m, double c[], double w[] );
string p02_title ( );
double *p03_d ( int m, int id, double c[], double w[], int n, double x[] );
double *p03_f ( int m, double c[], double w[], int n, double x[] );
double p03_q ( int m, double c[], double w[] );
string p03_title ( );
double *p04_d ( int m, int id, double c[], double w[], int n, double x[] );
double *p04_f ( int m, double c[], double w[], int n, double x[] );
double p04_q ( int m, double c[], double w[] );
string p04_title ( );
double *p05_d ( int m, int id, double c[], double w[], int n, double x[] );
double *p05_f ( int m, double c[], double w[], int n, double x[] );
double p05_q ( int m, double c[], double w[] );
string p05_title ( );
double *p06_d ( int m, int id, double c[], double w[], int n, double x[] );
double *p06_f ( int m, double c[], double w[], int n, double x[] );
double p06_q ( int m, double c[], double w[] );
string p06_title ( );
double r8_error ( double x );
double r8_errorc ( double x );
double r8_mach ( int i );
void tuple_next ( int m1, int m2, int n, int &rank, int x[] );
