char ch_cap ( char ch );
double euler_constant ( );
unsigned long get_seed ( );
int i4_huge ( );
int i4_log_2 ( int i );
int i4_power ( int i, int j );
double *i4_to_halton_number_sequence_new ( int seed, int base, int n );
int *i4vec_indicator_new ( int n );
double p00_even ( int prob, int int_num );
double p00_exact ( int prob );
double *p00_fun ( int prob, int n, double x[] );
double p00_gauss_legendre ( int prob, int int_num );
double p00_halton ( int prob, int int_num );
void p00_lim ( int prob, double &a, double &b );
double p00_midpoint ( int prob, int int_num );
double p00_montecarlo ( int prob, int int_num );
int p00_prob_num ( );
double p00_simpson ( int prob, int int_num );
double p00_trapezoid ( int prob, int int_num );
double p01_exact ( );
double *p01_fun ( int n, double x[] );
void p01_lim ( double &a, double &b );
double p02_exact ( );
double *p02_fun ( int n, double x[] );
void p02_lim ( double &a, double &b );
double p03_exact ( );
double *p03_fun ( int n, double x[] );
void p03_lim ( double &a, double &b );
double p04_exact ( );
double *p04_fun ( int n, double x[] );
void p04_lim ( double &a, double &b );
double p05_exact ( );
double *p05_fun ( int n, double x[] );
void p05_lim ( double &a, double &b );
double p06_exact ( );
double *p06_fun ( int n, double x[] );
void p06_lim ( double &a, double &b );
double p07_exact ( );
double *p07_fun ( int n, double x[] );
void p07_lim ( double &a, double &b );
double p08_exact ( );
double *p08_fun ( int n, double x[] );
void p08_lim ( double &a, double &b );
double p09_exact ( );
double *p09_fun ( int n, double x[] );
void p09_lim ( double &a, double &b );
double p10_exact ( );
double *p10_fun ( int n, double x[] );
void p10_lim ( double &a, double &b );
double p11_exact ( );
double *p11_fun ( int n, double x[] );
void p11_lim ( double &a, double &b );
double p12_exact ( );
double *p12_fun ( int n, double x[] );
void p12_lim ( double &a, double &b );
double p13_exact ( );
double *p13_fun ( int n, double x[] );
void p13_lim ( double &a, double &b );
double p14_exact ( );
double *p14_fun ( int n, double x[] );
void p14_lim ( double &a, double &b );
double p15_exact ( );
double *p15_fun ( int n, double x[] );
void p15_lim ( double &a, double &b );
double p16_exact ( );
double *p16_fun ( int n, double x[] );
void p16_lim ( double &a, double &b );
double p17_exact ( );
double *p17_fun ( int n, double x[] );
void p17_lim ( double &a, double &b );
double p18_exact ( );
double *p18_fun ( int n, double x[] );
void p18_lim ( double &a, double &b );
double p19_exact ( );
double *p19_fun ( int n, double x[] );
void p19_lim ( double &a, double &b );
double p20_exact ( );
double *p20_fun ( int n, double x[] );
void p20_lim ( double &a, double &b );
double p21_exact ( );
double *p21_fun ( int n, double x[] );
void p21_lim ( double &a, double &b );
double p22_exact ( );
double *p22_fun ( int n, double x[] );
void p22_lim ( double &a, double &b );
double p23_exact ( );
double *p23_fun ( int n, double x[] );
void p23_lim ( double &a, double &b );
double p24_exact ( );
double *p24_fun ( int n, double x[] );
void p24_lim ( double &a, double &b );
double p25_exact ( );
double *p25_fun ( int n, double x[] );
void p25_lim ( double &a, double &b );
double p26_exact ( );
double *p26_fun ( int n, double x[] );
void p26_lim ( double &a, double &b );
double p27_exact ( );
double *p27_fun ( int n, double x[] );
void p27_lim ( double &a, double &b );
double p28_exact ( );
double *p28_fun ( int n, double x[] );
void p28_lim ( double &a, double &b );
double p29_exact ( );
double *p29_fun ( int n, double x[] );
void p29_lim ( double &a, double &b );
double p30_exact ( );
double *p30_fun ( int n, double x[] );
void p30_lim ( double &a, double &b );
double p31_exact ( );
double *p31_fun ( int n, double x[] );
void p31_lim ( double &a, double &b );
double p32_exact ( );
double *p32_fun ( int n, double x[] );
void p32_lim ( double &a, double &b );
double p33_exact ( );
double *p33_fun ( int n, double x[] );
void p33_lim ( double &a, double &b );
double p34_exact ( );
double *p34_fun ( int n, double x[] );
void p34_lim ( double &a, double &b );
double p35_exact ( );
double *p35_fun ( int n, double x[] );
void p35_lim ( double &a, double &b );
double p36_exact ( );
double *p36_fun ( int n, double x[] );
void p36_lim ( double &a, double &b );
void p36_param ( string action, string name, double &value );
double p36_param_get ( );
void p36_param_set ( double alpha );
double p37_exact ( );
double *p37_fun ( int n, double x[] );
void p37_lim ( double &a, double &b );
void p37_param ( string action, string name, double &value );
double p37_param_get ( );
void p37_param_set ( double alpha );
double p38_exact ( );
double *p38_fun ( int n, double x[] );
void p38_lim ( double &a, double &b );
void p38_param ( string action, string name, double &value );
double p38_param_get ( );
void p38_param_set ( double alpha );
double p39_exact ( );
double *p39_fun ( int n, double x[] );
void p39_lim ( double &a, double &b );
void p39_param ( string action, string name, double &value );
double p39_param_get ( );
void p39_param_set ( double alpha );
double p40_exact ( );
double *p40_fun ( int n, double x[] );
void p40_lim ( double &a, double &b );
void p40_param ( string action, string name, double &value );
double p40_param_get ( );
void p40_param_set ( double alpha );
double p41_exact ( );
double *p41_fun ( int n, double x[] );
void p41_lim ( double &a, double &b );
void p41_param ( string action, string name, double &value );
double p41_param_get ( );
void p41_param_set ( double alpha );
double p42_exact ( );
double *p42_fun ( int n, double x[] );
void p42_lim ( double &a, double &b );
void p42_param ( string action, string name, double &value );
double p42_param_get ( );
void p42_param_set ( double alpha );
double p43_exact ( );
double *p43_fun ( int n, double x[] );
void p43_lim ( double &a, double &b );
void p43_param ( string action, string name, double &value );
double p43_param_get ( );
void p43_param_set ( double alpha );
double p44_exact ( );
double *p44_fun ( int n, double x[] );
void p44_lim ( double &a, double &b );
void p44_param ( string action, string name, double &value );
double p44_param_get ( );
void p44_param_set ( double alpha );
double p45_exact ( );
double *p45_fun ( int n, double x[] );
void p45_lim ( double &a, double &b );
void p45_param ( string action, string name, double &value );
double p45_param_get ( );
void p45_param_set ( double alpha );
double p46_exact ( );
double *p46_fun ( int n, double x[] );
void p46_lim ( double &a, double &b );
void p46_param ( string action, string name, double &value );
double p46_param_get ( );
void p46_param_set ( double alpha );
double p47_exact ( );
double *p47_fun ( int n, double x[] );
void p47_lim ( double &a, double &b );
double p48_exact ( );
double *p48_fun ( int n, double x[] );
void p48_lim ( double &a, double &b );
double p49_exact ( );
double *p49_fun ( int n, double x[] );
void p49_lim ( double &a, double &b );
double p50_exact ( );
double *p50_fun ( int n, double x[] );
void p50_lim ( double &a, double &b );
double p51_exact ( );
double *p51_fun ( int n, double x[] );
void p51_lim ( double &a, double &b );
double p52_exact ( );
double *p52_fun ( int n, double x[] );
void p52_lim ( double &a, double &b );
double p53_exact ( );
double *p53_fun ( int n, double x[] );
void p53_lim ( double &a, double &b );
double p54_exact ( );
double *p54_fun ( int n, double x[] );
void p54_lim ( double &a, double &b );
double p55_exact ( );
double *p55_fun ( int n, double x[] );
void p55_lim ( double &a, double &b );
void p55_param ( string action, string name, double &value );
double p56_exact ( );
double *p56_fun ( int n, double x[] );
void p56_lim ( double &a, double &b );
double p57_exact ( );
double *p57_fun ( int n, double x[] );
void p57_lim ( double &a, double &b );
double r8_abs ( double x );
double r8_add ( double x, double y );
double r8_aint ( double x );
void r8_b0mp ( double x, double &ampl, double &theta );
double r8_besj0 ( double x );
double r8_ci ( double x );
double r8_csevl ( double x, double cs[], int n );
double r8_epsilon ( );
double r8_erf ( double x );
double r8_erfc ( double x );
void r8_gaml ( double &xmin, double &xmax );
double r8_gamma ( double x );
double r8_huge ( );
int r8_inits ( double dos[], int nos, double eta );
double r8_lgmc ( double x );
double r8_mach ( int i );
double r8_max ( double x, double y );
double r8_min ( double x, double y );
double r8_sech ( double x );
double r8_si ( double x );
void r8_sifg ( double x, double &f, double &g );
double r8vec_dot_product ( int n, double a1[], double a2[] );
double *r8vec_linspace_new ( int n, double a_first, double a_last );
double r8vec_sum ( int n, double a[] );
double *r8vec_uniform_01_new ( int n, int *seed );
bool s_eqi ( string s1, string s2 );
void timestamp ( );
