double *p00_f ( int prob, int n, double x[] );
int p00_prob_num ( );
string p00_title ( int prob );
double *p01_f ( int n, double x[] );
string p01_title ( );
double *p02_f ( int n, double x[] );
string p02_title ( );
double *p03_f ( int n, double x[] );
string p03_title ( );
double *p04_f ( int n, double x[] );
string p04_title ( );
double *p05_f ( int n, double x[] );
string p05_title ( );
double *p06_f ( int n, double x[] );
string p06_title ( );
double *p07_f ( int n, double x[] );
string p07_title ( );
double *p08_f ( int n, double x[] );
string p08_title ( );
