void legendre_dr_compute ( int n, double x[], double w[] );
double p00_exact ( int problem );
void p00_fun ( int problem, int n, double x[], double fx[] );
void p00_lim ( int problem, double a[2], double b[2] );
int p00_problem_num ( );
double p01_exact ( );
void p01_fun ( int n, double x[], double fx[] );
void p01_lim ( double a[2], double b[2] );
double p02_exact ( );
void p02_fun ( int n, double x[], double fx[] );
void p02_lim ( double a[2], double b[2] );
double p03_exact ( );
void p03_fun ( int n, double x[], double fx[] );
void p03_lim ( double a[2], double b[2] );
double p04_exact ( );
void p04_fun ( int n, double x[], double fx[] );
void p04_lim ( double a[2], double b[2] );
double p05_exact ( );
void p05_fun ( int n, double x[], double fx[] );
void p05_lim ( double a[2], double b[2] );
double p06_exact ( );
void p06_fun ( int n, double x[], double fx[] );
void p06_lim ( double a[2], double b[2] );
double p07_exact ( );
void p07_fun ( int n, double x[], double fx[] );
void p07_lim ( double a[2], double b[2] );
double p08_exact ( );
void p08_fun ( int n, double x[], double fx[] );
void p08_lim ( double a[2], double b[2] );
double r8_abs ( double x );
double r8_csevl ( double x, double a[], int n );;
double r8_erf ( double x );
double r8_erfc ( double x );
int r8_inits ( double dos[], int nos, double eta );
double r8_mach ( int i );
double *r8mat_uniform_01 ( int m, int n, int *seed );
double r8vec_sum ( int n, double a[] );
void timestamp ( );
