int a_to_i4 ( char ch );
int base_to_i4 ( char *s, int base );
int binary_to_i4 ( string s );
void byte_to_int ( unsigned char *bvec, unsigned int *ival );
char ch_cap ( char c );
void ch_count_cvec_add ( int n, unsigned char cvec[], int count[256] );
void ch_count_file_add ( string file_name, int count[256] );
void ch_count_init ( int count[256] );
void ch_count_print ( int count[], char *title );
void ch_count_s_add ( unsigned char *s, int count[256] );
bool ch_eqi ( char c1, char c2 );
int ch_index_first ( string s, char c );
int ch_index_last ( string s, char c );
bool ch_is_alpha ( char c );
bool ch_is_alphanumeric ( char c );
bool ch_is_control ( char ch );
bool ch_is_digit ( char c );
bool ch_is_format_code ( char c );
bool ch_is_lower ( char c );
bool ch_is_printable ( char ch );
bool ch_is_space ( char c );
bool ch_is_upper ( char c );
char ch_low ( char c );
int ch_pad ( int *char_index, int *null_index, char *s, int max_string );
char ch_read ( FILE *filein );
int ch_roman_to_i4 ( char ch );
char ch_scrabble ( int tile );
int ch_scrabble_frequency ( char ch );
int ch_scrabble_points ( char ch );
char ch_scrabble_select ( int *seed );
void ch_swap ( char *c1, char *c2 );
int ch_to_digit ( char c );
int ch_to_digit_bin ( char c );
int ch_to_digit_oct ( char c );
char ch_to_rot13 ( char ch );
int ch_to_scrabble ( char ch );
char ch_uniform ( char clo, char chi, int *seed );
int ch_write ( FILE *fileout, char c );
void charstar_adjustl ( char *s1 );
char *charstar_cat ( char *s1, char *s2 );
bool charstar_eqi ( char *s1, char *s2 );
int charstar_len_trim ( char *s );
char digit_bin_to_ch ( int i );
char digit_inc ( char c );
char digit_oct_to_ch ( int i );
char digit_to_ch ( int i );
unsigned int getbits ( unsigned int x, int p, int n );
int hex_digit_to_i4 ( char c );
string hex_to_binary_digits ( char hex_digit );
int hex_to_i4 ( string s );
int i4_huge ( );
int i4_input ( string prompt, int &ierror );
int i4_log_10 ( int i );
int i4_max ( int i1, int i2 );
int i4_min ( int i1, int i2 );
void i4_swap ( int *i, int *j );
char i4_to_a ( int i );
char i4_to_amino_code ( int i );
char i4_to_hex_digit ( int i );
char i4_to_isbn ( int i );
string i4_to_month_abb ( int i );
string i4_to_month_name ( int i );
string i4_to_s ( int i );
string i4_to_s0 ( int i, int digits );
string i4_to_string ( int i4 );
string i4_to_unary ( int i4 );
int i4_uniform ( int a, int b, int *seed );
int *i4vec_indicator ( int n );
void i4vec_print ( int n, int a[], string title );
void int_to_byte ( unsigned int ival, unsigned char *bvec );
int isbn_to_i4 ( char c );
bool perm_check ( int n, int p[] );
int *perm_uniform ( int n, int *seed );
void print_sizes ( );
float r4_abs ( float x );
int r4_nint ( float x );
string r4_to_string ( float r4 );
string r8_to_string ( double r8 );
double r8_uniform_01 ( int *seed );
float reverse_bytes_float ( float x );
int reverse_bytes_int ( int x );
string s_adjustl ( string s );
bool s_begin ( string s1, string s2 );
void s_behead_substring ( char *s, char *sub );
void s_blank_delete ( char *s );
string s_blanks_delete ( string s );
string s_cap ( string s );
int s_ch_count ( string s, char ch );
string s_ch_delete ( string s, char ch );
string s_control_blank ( string s );
bool s_eqi ( string s1, string s2 );
string s_escape_tex ( string s1 );
int s_first_ch ( string s, char ch );
char *s_first_nonblank ( char *s );
void s_inc_c ( char *s );
void s_inc_n ( char *s );
string s_last_ch ( string s, char ch );
int s_len_trim ( string s );
string s_low ( string s );
string s_newline_to_null ( string s );
string s_nonalpha_delete ( string s );
string s_replace_ch ( string s, char c1, char c2 );
string s_reverse ( string s );
int s_scrabble_points ( string );
bool s_s_subanagram ( string s1, string s2 );
bool s_s_subanagram_sorted ( string s1, string s2 );
string s_sort_a ( string s );
char *s_substring ( char *s, int a, int b );
string s_tab_blank ( string s );
void s_to_format ( char *s, int *r, char *code, int *w, int *m );
int s_to_i4 ( string s, int &last, bool &error );
bool s_to_i4vec ( string s, int n, int ivec[] );
bool s_to_l ( string s );
float s_to_r4 ( string s, int &lchar, bool &error );
bool s_to_r4vec ( string s, int n, float rvec[] );
double s_to_r8 ( string s, int &lchar, bool &error );
bool s_to_r8vec ( string s, int n, double rvec[] );
string s_to_rot13 ( string s );
string s_trim ( string s );
string s_word_cap ( string s );
int s_word_count ( string s );
void s_word_extract_first ( string s, string &s1, string &s2 );
void sort_heap_external ( int n, int *indx, int *i, int *j, int isgn );
float swap_bytes_float ( float x );
int swap_bytes_int ( int x );
void timestamp ( );
string word_next_read ( string s, bool *done );

