void comp_next ( int n, int k, int a[], bool *more, int *h, int *t );
int i4_choose ( int n, int k );
int i4_max ( int i1, int i2 );
int i4_min ( int i1, int i2 );
int sparse_grid_cc_se_size ( int dim_num, int level_max );
int sparse_grid_cfn_e_size ( int dim_num, int level_max );
int sparse_grid_f2_se_size ( int dim_num, int level_max );
int sparse_grid_gp_se_size ( int dim_num, int level_max );
int sparse_grid_ofn_e_size ( int dim_num, int level_max );
int sparse_grid_onn_e_size ( int dim_num, int level_max );
int sparse_grid_onn_l_size ( int dim_num, int level_max );
int sparse_grid_own_e_size ( int dim_num, int level_max );
int sparse_grid_own_l_size ( int dim_num, int level_max );
int sparse_grid_own_ls_size ( int dim_num, int level_max );
void timestamp ( );
