double angle_shift ( double alpha, double beta );
double arccos_cordic ( double t, int n );
void arccos_values ( int *n_data, double *x, double *fx );
double arcsin_cordic ( double t, int n );
void arcsin_values ( int *n_data, double *x, double *fx );
double arctan_cordic ( double x, double y, int n );
void arctan_values ( int *n_data, double *x, double *fx );
double cbrt_cordic ( double x, int n );
void cbrt_values ( int *n_data, double *x, double *fx );
void cos_values ( int *n_data, double *x, double *fx );
void cossin_cordic ( double beta, int n, double *c, double *s );
double exp_cordic ( double x, int n );
void exp_values ( int *n_data, double *x, double *fx );
int i4_huge ( void );
int i4_min ( int i1, int i2 );
double ln_cordic ( double x, int n );
void ln_values ( int *n_data, double *x, double *fx );
double r8_uniform_01 ( int *seed );
void sin_values ( int *n_data, double *x, double *fx );
double sqrt_cordic ( double x, int n );
void sqrt_values ( int *n_data, double *x, double *fx );
double tan_cordic ( double beta, int n );
void tan_values ( int *n_data, double *x, double *fx );
void timestamp ( void );
