double p00_f ( int problem, double x );
double p00_f1 ( int problem, double x );
double p00_f1_dif ( int problem, double x );
double p00_f2 ( int problem, double x );
double p00_f2_dif ( int problem, double x );
double p00_fmin ( double *a, double *b, int problem, double tol );
void p00_interval ( int problem, double *a, double *b );
int p00_problem_num ( );
void p00_sol ( int problem, int *know, double *x );
double p00_start ( int problem );
string p00_title ( int problem );
double p01_f ( double x );
double p01_f1 ( double x );
double p01_f2 ( double x );
void p01_interval ( double *a, double *b );
void p01_sol ( int *know, double *x );
double p01_start ( );
string p01_title ( );
double p02_f ( double x );
double p02_f1 ( double x );
double p02_f2 ( double x );
void p02_interval ( double *a, double *b );
void p02_sol ( int *know, double *x );
double p02_start ( );
string p02_title ( );
double p03_f ( double x );
double p03_f1 ( double x );
double p03_f2 ( double x );
void p03_interval ( double *a, double *b );
void p03_sol ( int *know, double *x );
double p03_start ( );
string p03_title ( );
double p04_f ( double x );
double p04_f1 ( double x );
double p04_f2 ( double x );
void p04_interval ( double *a, double *b );
void p04_sol ( int *know, double *x );
double p04_start ( );
string p04_title ( );
double p05_f ( double x );
double p05_f1 ( double x );
double p05_f2 ( double x );
void p05_interval ( double *a, double *b );
void p05_sol ( int *know, double *x );
double p05_start ( );
string p05_title ( );
double p06_f ( double x );
double p06_f1 ( double x );
double p06_f2 ( double x );
void p06_interval ( double *a, double *b );
void p06_sol ( int *know, double *x );
double p06_start ( );
string p06_title ( );
double p07_f ( double x );
double p07_f1 ( double x );
double p07_f2 ( double x );
void p07_interval ( double *a, double *b );
void p07_sol ( int *know, double *x );
double p07_start ( );
string p07_title ( );
double p08_f ( double x );
double p08_f1 ( double x );
double p08_f2 ( double x );
void p08_interval ( double *a, double *b );
void p08_sol ( int *know, double *x );
double p08_start ( );
string p08_title ( );
double p09_f ( double x );
double p09_f1 ( double x );
double p09_f2 ( double x );
void p09_interval ( double *a, double *b );
void p09_sol ( int *know, double *x );
double p09_start ( );
string p09_title ( );
double p10_f ( double x );
double p10_f1 ( double x );
double p10_f2 ( double x );
void p10_interval ( double *a, double *b );
void p10_sol ( int *know, double *x );
double p10_start ( );
string p10_title ( );
double p11_f ( double x );
double p11_f1 ( double x );
double p11_f2 ( double x );
void p11_interval ( double *a, double *b );
void p11_sol ( int *know, double *x );
double p11_start ( );
string p11_title ( );
double r8_abs ( double x );
double r8_epsilon ( );
double r8_sign ( double x );
void timestamp ( );
