int *i4vec_uniform_ab_new ( int n, int a, int b, int &seed );
double *monomial_value ( int m, int n, int e[], double x[] );
double r8_gamma ( double x );
double *r8mat_normal_01_new ( int m, int n, int &seed );
double *r8vec_normal_01_new ( int n, int &seed );
double r8vec_sum ( int n, double a[] );
double *r8vec_uniform_01_new ( int n, int &seed );
double sphere01_area ( );
double sphere01_monomial_integral ( int e[3] );
double *sphere01_sample ( int n, int &seed );
void timestamp ( );
