double hyperball01_monomial_integral ( int m, int e[] );
double *hyperball01_sample ( int m, int n, int &seed );
double hyperball01_volume ( int m );
int i4vec_sum ( int n, int a[] );
int *i4vec_uniform_ab_new ( int n, int a, int b, int &seed );
double *monomial_value ( int m, int n, int e[], double x[] );
double r8_gamma ( double x );
double r8_uniform_01 ( int &seed );
double *r8mat_normal_01_new ( int m, int n, int &seed );
double *r8vec_normal_01_new ( int n, int &seed );
double r8vec_sum ( int n, double a[] );
double *r8vec_uniform_01_new ( int n, int &seed );
void timestamp ( );
