double *p00_a ( int prob, int m, int n );
double *p00_b ( int prob, int m );
int p00_m ( int prob );
int p00_n ( int prob );
int p00_prob_num ( );
double *p00_x ( int prob, int n );
double *p01_a ( int m, int n );
double *p01_b ( int m );
int p01_m ( );
int p01_n ( );
double *p01_x ( int n );
double *p02_a ( int m, int n );
double *p02_b ( int m );
int p02_m ( );
int p02_n ( );
double *p02_x ( int n );
double *p03_a ( int m, int n );
double *p03_b ( int m );
int p03_m ( );
int p03_n ( );
double *p03_x ( int n );
double *p04_a ( int m, int n );
double *p04_b ( int m );
int p04_m ( );
int p04_n ( );
double *p04_x ( int n );
double *p05_a ( int m, int n );
double *p05_b ( int m );
int p05_m ( );
int p05_n ( );
double *p05_x ( int n );
double *p06_a ( int m, int n );
double *p06_b ( int m );
int p06_m ( );
int p06_n ( );
double *p06_x ( int n );

