int bicycle_lock ( int c );
int combination_lock ( int m, int n, int c[] );
void combination_next ( int m, int base, int a[], bool &more );
int get_seed ( );
int i4_max ( int i1, int i2 );
int i4_min ( int i1, int i2 );
int i4_power ( int i, int j );
int i4_uniform ( int a, int b, int &seed );
bool i4vec_eq ( int n, int a1[], int a2[] );
void i4vec_print ( int n, int a[], string title );
float r4_abs ( float x );
int r4_nint ( float x );
void timestamp ( );
