void p00_ab ( int problem, int m, double a[], double b[] );
double *p00_f ( int problem, int m, int n, double x[] );
int p00_m ( int problem );
int p00_problem_num ( );
double *p00_sol ( int problem, int m, int &know );
string p00_title ( int problem );
void p01_ab ( int m, double a[], double b[] );
double *p01_f ( int m, int n, double x[] );
int p01_m ( );
double *p01_sol ( int m, int &know );
string p01_title ( );
void p02_ab ( int m, double a[], double b[] );
double *p02_f ( int m, int n, double x[] );
int p02_m ( );
double *p02_sol ( int m, int &know );
string p02_title ( );
void p03_ab ( int m, double a[], double b[] );
double *p03_f ( int m, int n, double x[] );
int p03_m ( );
double *p03_sol ( int m, int &know );
string p03_title ( );
void p04_ab ( int m, double a[], double b[] );
double *p04_f ( int m, int n, double x[] );
int p04_m ( );
double *p04_sol ( int m, int &know );
string p04_title ( );
void p05_ab ( int m, double a[], double b[] );
double *p05_f ( int m, int n, double x[] );
int p05_m ( );
double *p05_sol ( int m, int &know );
string p05_title ( );
void p06_ab ( int m, double a[], double b[] );
double *p06_f ( int m, int n, double x[] );
int p06_m ( );
double *p06_sol ( int m, int &know );
string p06_title ( );
void p07_ab ( int m, double a[], double b[] );
double *p07_f ( int m, int n, double x[] );
int p07_m ( );
double *p07_sol ( int m, int &know );
string p07_title ( );
void p08_ab ( int m, double a[], double b[] );
double *p08_f ( int m, int n, double x[] );
int p08_m ( );
double *p08_sol ( int m, int &know );
string p08_title ( );
double *r8col_uniform_new ( int m, int n, double a[], double b[], int *seed );
double r8vec_max ( int n, double r8vec[] );
double r8vec_min ( int n, double r8vec[] );
void timestamp ( );
