double fx1 ( double x );
double fx2 ( double x );
double fx3 ( double x );
double fx4 ( double x );
double fx5 ( double x );
double fx6 ( double x );
double fx7 ( double x );
double fxy1 ( double x, double y );
double fxy2 ( double x, double y );
double fxy3 ( double x, double y );
double fxy4 ( double x, double y );
double fxy5 ( double x, double y );
double fxyz1 ( double x, double y, double z );
double *fx1_vec ( int n, double x[] );
double *fx2_vec ( int n, double x[] );
double *fx3_vec ( int n, double x[] );
double *fx4_vec ( int n, double x[] );
double *fx5_vec ( int n, double x[] );
double *fx6_vec ( int n, double x[] );
double *fx7_vec ( int n, double x[] );
double *fxy1_vec ( int n, double x[], double y[] );
double *fxy2_vec ( int n, double x[], double y[] );
double *fxy3_vec ( int n, double x[], double y[] );
double *fxy4_vec ( int n, double x[], double y[] );
double *fxy5_vec ( int n, double x[], double y[] );
double *fxyz1_vec ( int n, double x[], double y[], double z[] );
double *r8vec_copy_new ( int n, double a1[] );
double *r8vec_linspace_new ( int n, double a, double b );
double *r8vec_uniform_ab_new ( int n, double a, double b, int &seed );
void timestamp ( );

