char ch_cap ( char c );
bool ch_eqi ( char c1, char c2 );
bool ch_is_digit ( char c );
char ch_low ( char c );
int ch_to_digit ( char c );
char ch_to_rot13 ( char ch );
char digit_inc ( char c );
char digit_to_ch ( int i );
int file_char_count ( string filename );
int file_column_count ( string filename );
int file_delete ( string filename );
bool file_exist ( string filename );
string file_line_uniform ( string filename, int *seed,
  int *line_index, int *line_num );
int file_line_width ( string filename );
int file_para_count ( string filename );
int file_row_count ( string filename );
int file_sequence_delete ( string filename );
void file_sequence_size ( string filename, int *file_dim, int *file_num );
int file_word_count ( string filename );
void filename_dec ( string *filename );
void filename_ext_get ( string filename, int *i, int *j );
string filename_ext_swap ( string filename, string ext );
void filename_inc ( string *filename );
void filename_inc_nowrap ( string *filename );
int i4_max ( int i1, int i2 );
int i4_min ( int i1, int i2 );
int i4_uniform ( int b, int c, int *seed );
void number_inc ( string s );
float r4_abs ( float x );
int r4_nint ( float x );
int r8_nint ( double x );
double r8_uniform_01 ( int *seed );
bool s_eqi ( string s1, string s2 );
int s_len_trim ( string s );
void s_low ( string s );
string s_reverse ( string s );
int s_to_i4 ( string s, int *last, bool *error );
bool s_to_i4vec ( string s, int n, int ivec[] );
double s_to_r8 ( string s, int *lchar, bool *error );
bool s_to_r8vec ( string s, int n, double rvec[] );
void s_to_rot13 ( string s );
int s_word_count ( string s );
void timestamp ( );
