void hermite_compute ( int order, double xtab[], double weight[] );
void hermite_recur ( double *p2, double *dp2, double *p1, double x, 
  int order );
void hermite_root ( double *x, int order, double *dp2, double *p1 );
void hermite_compute ( int order, double xtab[], double weight[] );
int i4_factorial2 ( int n );
double p00_exact ( int problem );
double p00_exp_transform ( int problem, int order );
void p00_fun ( int problem, int option, int n, double x[], double f[] );
double p00_gauss_hermite ( int problem, int order );
double p00_monte_carlo ( int problem, int order );
int p00_problem_num ( );
double p00_turing ( int problem, double h, double tol, int *n );
string p00_title ( int problem );
double p01_exact ( );
void p01_fun ( int option, int n, double x[], double f[] );
string p01_title ( );
double p02_exact ( );
void p02_fun ( int option, int n, double x[], double f[] );
string p02_title ( );
double p03_exact ( );
void p03_fun ( int option, int n, double x[], double f[] );
string p03_title ( );
double p04_exact ( );
void p04_fun ( int option, int n, double x[], double f[] );
string p04_title ( );
double p05_exact ( );
void p05_fun ( int option, int n, double x[], double f[] );
string p05_title ( );
double p06_exact ( );
void p06_fun ( int option, int n, double x[], double f[] );
void p06_param ( char action, char name, int *value );
string p06_title ( );
double p07_exact ( );
void p07_fun ( int option, int n, double x[], double f[] );
string p07_title ( );
double p08_exact ( );
void p08_fun ( int option, int n, double x[], double f[] );
string p08_title ( );
double r8_abs ( double x );
double r8_epsilon ( );
double r8_gamma ( double x );
double r8_huge ( );
double r8vec_dot_product ( int n, double a1[], double a2[] );
double *r8vec_normal_01_new ( int n, int *seed );
void r8vec_reverse ( int n, double a[] );
double r8vec_sum ( int n, double a[] );
double *r8vec_uniform_01_new ( int n, int *seed );
void timestamp ( );
