int get_problem_num ( void );
unsigned long get_seed ( void );
int i4_huge ( void );
int i4_power ( int i, int j );
double *p00_fun ( int problem, int n, double p[] );
double p00_monte_carlo ( int problem, int n, int *seed );
int p00_singularity ( int problem );
char *p00_title ( int problem );
void p00_vertex_sub ( int problem, int level, int *n, double *result );
double *p00_vertices ( int problem );
double p00_wandzura05_sub ( int problem, int level, int *n );
double *p01_fun ( int n, double p[] );
char *p01_title ( void );
double *p01_vertices ( void );
double *p02_fun ( int n, double p[] );
char *p02_title ( void );
double *p02_vertices ( void );
double *p03_fun ( int n, double p[] );
char *p03_title ( void );
double *p03_vertices ( void );
double *p04_fun ( int n, double p[] );
char *p04_title ( void );
double *p04_vertices ( void );
double *p05_fun ( int n, double p[] );
char *p05_title ( void );
double *p05_vertices ( void );
double *p06_fun ( int n, double p[] );
char *p06_title ( void );
double *p06_vertices ( void );
double *p07_fun ( int n, double p[] );
char *p07_title ( void );
double *p07_vertices ( void );
double *p08_fun ( int n, double p[] );
char *p08_title ( void );
double *p08_vertices ( void );
double *p09_fun ( int n, double p[] );
char *p09_title ( void );
double *p09_vertices ( void );
double *p10_fun ( int n, double p[] );
char *p10_title ( void );
double *p10_vertices ( void );
double *p11_fun ( int n, double p[] );
char *p11_title ( void );
double *p11_vertices ( void );
double *p12_fun ( int n, double p[] );
char *p12_title ( void );
double *p12_vertices ( void );
double *p13_fun ( int n, double p[] );
char *p13_title ( void );
double *p13_vertices ( void );
double *p14_fun ( int n, double p[] );
char *p14_title ( void );
double *p14_vertices ( void );
double *p15_fun ( int n, double p[] );
char *p15_title ( void );
double *p15_vertices ( void );
double *p16_fun ( int n, double p[] );
char *p16_title ( void );
double *p16_vertices ( void );
double *p17_fun ( int n, double p[] );
char *p17_title ( void );
double *p17_vertices ( void );
double *p18_fun ( int n, double p[] );
char *p18_title ( void );
double *p18_vertices ( void );
double *p19_fun ( int n, double p[] );
char *p19_title ( void );
double *p19_vertices ( void );
double *p20_fun ( int n, double p[] );
char *p20_title ( void );
double *p20_vertices ( void );
double *p21_fun ( int n, double p[] );
char *p21_title ( void );
double *p21_vertices ( void );
double *p22_fun ( int n, double p[] );
char *p22_title ( void );
double *p22_vertices ( void );
double r8_abs ( double x );
double r8_uniform_01 ( int *seed );
void r8mat_mxm ( int n1, int n2, int n3, double a[], double b[], double c[] );
void r8mat_mxv ( int m, int n, double a[], double x[], double ax[] );
void r8vec_copy ( int n, double a1[], double a2[] );
double r8vec_dot ( int n, double a1[], double a2[] );
double r8vec_sum ( int n, double a[] );
double *r8vec_uniform_01 ( int n, int *seed );
unsigned long random_initialize ( unsigned long seed );
void subtriangle_next ( int n, bool *more, int *i1, int *j1, int *i2, int *j2, 
  int *i3, int *j3 );
void timestamp ( void );
double triangle_area ( double t[2*3] );
double *triangle_sample ( double t[2*3], int n, int *seed );

